### ISSUE TITLE
event to dispatch when permission has been granted

### ISSUE THREAD

**Issue by loudoweb** [player-03/android6permissions#2]
Is it possible to dispatch an event when permission has been granted so we can resume the app?

**Comment by player-03** [comment]
Not implemented, but it ought to be possible. I haven't looked at this repo in a while, perhaps longer than that functionality existed.

**Comment by loudoweb** [comment]
I found this: https://www.geeksforgeeks.org/android-how-to-request-permissions-in-android-application/

**Comment by player-03** [comment]
Done, and released on Haxelib. (Requires development version of Lime, though.)

Edit: the Haxelib version shouldn't rely on the development version of Lime. I rewrote it so that it doesn't.
